// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZuu9tYu55YBqJomZyPiMMAuRJn3iNuc',
    appId: '1:223014453620:web:06ce31cea3b1277319ac21',
    messagingSenderId: '223014453620',
    projectId: 'pahom-51540',
    authDomain: 'pahom-51540.firebaseapp.com',
    storageBucket: 'pahom-51540.appspot.com',
    measurementId: 'G-98T0TPQ62H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkXU5VjAaL8fgiKbUkLJw_RSUjMuBBPD8',
    appId: '1:223014453620:android:58bdaf6f56f1741319ac21',
    messagingSenderId: '223014453620',
    projectId: 'pahom-51540',
    storageBucket: 'pahom-51540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKDckXeEpXwyUfXmE-JC4PUIosDrhwSzo',
    appId: '1:223014453620:ios:29384252a98455b819ac21',
    messagingSenderId: '223014453620',
    projectId: 'pahom-51540',
    storageBucket: 'pahom-51540.appspot.com',
    iosClientId: '223014453620-e195uqa3bvfi642dgp384rcbgmo3qn94.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKDckXeEpXwyUfXmE-JC4PUIosDrhwSzo',
    appId: '1:223014453620:ios:29384252a98455b819ac21',
    messagingSenderId: '223014453620',
    projectId: 'pahom-51540',
    storageBucket: 'pahom-51540.appspot.com',
    iosClientId: '223014453620-e195uqa3bvfi642dgp384rcbgmo3qn94.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );
}
